config/routes.rb
Rails.application.routes.draw do
  #get  '/help',    to: 'static_pages#help'
  get '/new_minion_form', to: 'minion_form#form'
  #get 'minion_form/form'

  get 'minion_mania/home'

  resources :minion
  resources :user

  root 'minion_mania#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minion.rb
# name, description, price
class Minion < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  #validates :name, presence: true , length:{maximum: 50}
  validates :uid, presence: true
  
    def initialize()
        super()
        rnd = ('a'..'z').to_a.shuffle[0..14].join
        self.uid = rnd
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  def hello
    render html: "Hello" 
  end
end

app/controllers/minion_controller.rb
class MinionController < ApplicationController
  def index
    listOfMinions = Minion.all
    render json: listOfMinions.to_json, status: :ok
  end

  def show
  end

  def new
  end
  #grava o minion a partir do json vindo do cliente. Se os dados estiverem 
  #incompletos dá um erro pro cliente;
  def create
    receivedObject = JSON.parse(request.body.read)
    @minion = Minion.new
    @minion.name = receivedObject["name"]
    @minion.description = receivedObject["description"]
    @minion.price = receivedObject["price"]
    if @minion.valid?
      @minion.save
      render json: @minion, status: :ok
    else
      err = @minion.errors.messages
      @errJson = {
        status: 400,
        code: "foobar",
        title: "loren ipsun?",
        detail: "babdjsabdnbasnbdnasb"
      }
      render json: @errJson, status: 400
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/minion_form_controller.rb
class MinionFormController < ApplicationController
  def form
  end
end

app/controllers/minion_mania_controller.rb
class MinionManiaController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end

  def new
    @newUser = User.new
    render json: @newUser.to_json
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minion_form_helper.rb
module MinionFormHelper
end

app/helpers/minion_helper.rb
module MinionHelper
end

app/helpers/minion_mania_helper.rb
module MinionManiaHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>MinionMania</title>
    <%= csrf_meta_tags %>
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="newHeader blueText hardBanana">
      <span  class="title hardBanana">MINION MANIA</span>
      <div class="newHeader-right hardBanana">
        <a href="#">Sing in</a>
        <a href="#">Carrinho</a>
       <%= link_to "Novo Minion",   new_minion_form_path %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/minion/create.html.erb
<h1>Minion#create</h1>
<p>Find me in app/views/minion/create.html.erb</p>

app/views/minion/destroy.html.erb
<h1>Minion#destroy</h1>
<p>Find me in app/views/minion/destroy.html.erb</p>

app/views/minion/edit.html.erb
<h1>Minion#edit</h1>
<p>Find me in app/views/minion/edit.html.erb</p>

app/views/minion/index.html.erb
<h1>Minion#index</h1>
<p>Find me in app/views/minion/index.html.erb</p>

app/views/minion/new.html.erb
<h1>Minion#new</h1>
<p>Find me in app/views/minion/new.html.erb</p>

app/views/minion/show.html.erb
<h1>Minion#show</h1>
<p>Find me in app/views/minion/show.html.erb</p>

app/views/minion/update.html.erb
<h1>Minion#update</h1>
<p>Find me in app/views/minion/update.html.erb</p>

app/views/minion_form/form.html.erb
<div class="jumbotron left softBanana newMinionForm">
  <h3>Criação de Minion</h3>
  <div class="form-group">
    <label for="minion_form_name">Nome</label>
    <input type="text" class="form-control" id="minion_form_name" 
          aria-describedby="minion_form_name_helper" placeholder="Name">
    <small id="minion_form_name_helper" class="form-text text-muted">
      Não pode ser nulo
    </small>   
  </div>
  <div class="form-group">
    <label for="minion_form_description">Descrição</label>
    <input type="text" class="form-control" id="minion_form_description" 
          aria-describedby="minion_form_description_helper" placeholder="Name">
    <small id="minion_form_description_helper" class="form-text text-muted">
      Não pode ser nulo
    </small>   
  </div>
  <div class="form-group">
    <label for="minion_form_price">Preço</label>
    <input type="text" class="form-control" id="minion_form_price" 
          aria-describedby="minion_form_price_helper" placeholder="Name">
    <small id="minion_form_price_helper" class="form-text text-muted">
      Não pode ser nulo, tem que ser ponto flutuante separado por . (não por virgula)
    </small>   
  </div>  
  <div id="new_minion_errors">
    
  </div>

  <div><button onclick="window.saveNewMinion()">Salvar</button></div>
</div>

app/views/minion_mania/home.html.erb
<div class="jumbotron center softBanana">
  <div class="form-inline">
    <input class="form-control" placeholder="nome do minion">
    <button class="btn btn-primary">Buscar</button>
  </div>
  <div class="container-fluid">
    <div id="minion_container" class="col red">
    </div>
  </div>
  
  <hr/>
  <div class="invisible">
      <div class="row minionRow" id="minionCardBase">
        <div class="col-xs-4 col-sm-4 ">
          <img class="img-responsive" src=<%=image_url('minion_placeholder.jpg')%>/>
        </div>
        <div class="col-xs-8 col-sm-8  minionDataBox">
          <div class="minionNamePrice"> 
            <div class="nameDiv">NOME MUITO GRANDE DEMAIS DA CONTA</div>
            <div class="priceDiv"><small class="priceDivText">PRECO</small></div>
          </div>
          <div class="minionButtons"> 
              <button class="btn btn-primary">+</button>
              <button class="btn btn-secondary">-</button>
          </div>
        </div>
      </div>
</div>
</div>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>